#!/bin/bash

echo "        **************************************** "
echo "        **************************************** "  
echo "        **                 ~;                 ** "       
echo "        **                ,/|\,               ** "   
echo "        **               ,/' |\ \,            ** "
echo "        **              ,/'   | |  \          ** "
echo "        **             ,/'     | |   |        ** "
echo "        **           ,/'       |/    |        ** "
echo "        **         ,/__________|-----' ,      ** "
echo "        **       ___.....-----''-----/        ** " 
echo "        **        \  Nino_Script    /         ** "
echo "        **   ~~-~^~^~~'~~^^~^~-'^~^~^'~-~^~^  ** "
echo "        **   ~-^'~^-~^~-^~^'^~^-^~^'^~^-~^    ** "
echo "        **           [0]                      ** "
echo "        **           [1]                      ** "
echo "        **           [2]                      ** "
echo "        **           [3]                      ** "               
echo "        **           [4]                      ** "
echo "        **         ► [5]                      ** "
echo "        **           [6]                      ** "
echo "        **           [7]                      ** "
echo "        **           [8]                      ** "
echo "        **           [9]                      ** "
echo "        **          [10] Udemy                ** "
echo "        **          [11] Bootcamp Netuno      ** "
echo "        **          [12]                      ** "
echo "        **          [13]                      ** "
echo "        **          [14] Scripts              ** "
echo "        **                                    ** "
echo "        **      CTRL + C ==>SAIR              ** "
echo "        **                                    ** "
echo "        **************************************** " 
echo "        **     Good job!!                     ** "
echo "        **************************************** "
echo "        **************************************** "

echo Digite o numero do projeto:
read numero
if     [ $numero == "0" ] 
then 
    echo "Atenção no Cluar sou colaborador!!!"
elif [ $numero == "1" ] 
then
    echo "Ótimo voce escolheu helipacity"
elif [ $numero == "2" ] 
then
    echo "Ótimo voce escolheu netbase"
elif [ $numero == "3" ]
then 
    echo "Ótimo voce escolheu o cluarnino"
elif [ $numero == "4" ]
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "5" ] 
then
    echo "Ótimo voce escolheu fullstack"
elif [ $numero == "6" ]
then 
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "7" ]  
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "8" ] 
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "9" ]
then 
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "10" ]
then
    cd
    cd Dev
    cd udemy
    code .  
    firefox https://www.udemy.com/course/curso-web/learn/
elif [ $numero == "11" ] 
then
    gnome-terminal -- bash -c "firefox https://dev.netuno.org/formation/3afd971f-dace-4dd2-adb2-1382d5cac494; exec bash"
    gnome-terminal -- bash -c "firefox http://luismijias.bootcamp.dev.netuno.org:20180; exec bash"
    ssh luismijias@bootcamp.dev.netuno.org -p 20122    
elif [ $numero == "12" ]
then 
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "13" ]
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "14" ] 
then
    cd ~/Dev/bin
    code .
else
 echo "Comando inválido :-\.Digite o número de um dos projetos acima ;-)."
fi

#*******Entrar automático no server**************
#>>>Parte do cliente(pc)
#vídeo auxilio https://www.youtube.com/watch?v=wSOAdqnYjeY
#Obs: dentro da pasta .ssh --> scp -P 20122 id_rsa.pub luismijias@135.181.217.178:~/.ssh/authorized_keys
#caminho reverso do servidor para a maquina :scp -P 20122 luismijias@135.181.217.178:~/.ssh/id_ed25519 id_ed25519
#>>>Parte do servidor
# crie o diretório --> mkdir .ssh
#crie o arquivo dentro da pastar .ssh --> touch authorized_keys
#$dê a autorização correta--> chmod 600 ~/.ssh/authorized_keys
#depois envie o arquivo do pc para o sevidor.
#$ sudo systemctl restart ssh
#https://linuxhint.com/configure-authorized-keys-ssh-ubuntu

# ****Abrir um terminal e executar um script ou comando****
# https://askubuntu.com/questions/974756/how-can-i-open-a-extra-console-and-run-a-program-in-it-with-one-command
