#!/bin/bash

echo "************************************************ "
echo "************************************************ "  
echo "        **                 ~;                 ** "       
echo "        **                ,/|\,               ** "   
echo "        **               ,/' |\ \,            ** "
echo "        **              ,/'   | |  \          ** "
echo "        **             ,/'     | |   |        ** "
echo "        **           ,/'       |/    |        ** "
echo "        **         ,/__________|-----' ,      ** "
echo "        **       ___.....-----''-----/        ** " 
echo "        **        \  Nino_Script    /         ** "
echo "        **   ~~-~^~^~~'~~^^~^~-'^~^~^'~-~^~^  ** "
echo "        **   ~-^'~^-~^~-^~^'^~^-^~^'^~^-~^    ** "
echo "        **           [0]                      ** "
echo "        **           [1]                      ** "
echo "        **           [2]                      ** "
echo "        **           [3]                      ** "               
echo "        **           [4]                      ** "
echo "        **         ► [5]                      ** "
echo "        **           [6]                      ** "
echo "        **           [7]                      ** "
echo "        **           [8]                      ** "
echo "        **           [9]                      ** "
echo "        **          [10] Udemy                ** "
echo "        **          [11]                      ** "
echo "        **          [12]                      ** "
echo "        **          [13]                      ** "
echo "        **          [14] Script               ** "
echo "        **                                    ** "
echo "        **      CTRL + C ==>SAIR              ** "
echo "        **                                    ** "
echo "        **************************************** " 
echo "        **     Good job!! Nino ;-)            ** "
echo "        **************************************** "
echo "        **************************************** "

echo Digite o numero do projeto:
read numero
if     [ $numero == "0" ] 
then 
    echo "Atenção no Cluar sou colaborador!!!"
elif [ $numero == "1" ] 
then
    echo "Ótimo voce escolheu helipacity"
elif [ $numero == "2" ] 
then
    echo "Ótimo voce escolheu netbase"
elif [ $numero == "3" ]
then 
    echo "Ótimo voce escolheu o cluarnino"
elif [ $numero == "4" ]
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "5" ] 
then
    echo "Ótimo voce escolheu fullstack"
elif [ $numero == "6" ]
then 
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "7" ]  
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "8" ] 
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "9" ]
then 
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "10" ]
then 
    cd
    cd Dev/udemy
    git add .
    git commit -m "commited whith script by pc ubunto_main"
    git push
    git status
elif [ $numero == "11" ] 
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero" 
elif [ $numero == "12" ]
then 
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "13" ]
then
    echo "Ótimo voce escolheu o cluar que é o projeto número: $numero"
elif [ $numero == "14" ] 
then
    cd ~/Dev/bin
    git add .
    git commit -m "automatic commit"
    git push
    git status
else
 echo "Comando inválido :-\.Digite o número de um dos projetos acima ;-)."
fi


# How to fix Git always asking for user credentials
# https://www.freecodecamp.org/portuguese/news/como-resolver-o-problema-de-o-git-pedir-sempre-as-credenciais-do-usuario/
# Clonar o repositório dentro de uma pasta Dev -->sudo git clone https://github.com/Luismijias/bin.git                            
# remover a pasta bin ->> sudo rm -r /usr/local/bin 
# crir um link da pasta bin que acabou de puxar do github no /usr/bin ->> 
sudo ln -s ~/Dev/bin/gitdev /usr/bin | sudo ln -s ~/Dev/bin/vs /usr/bin | sudo ln -s ~/Dev/bin/dev /usr/bin
